version: "3.9"

services:

    mssql-server:
        image: mcr.microsoft.com/mssql/server:2019-CU10-ubuntu-20.04
        container_name: mssql-server
        build:
            context: ../sql
            dockerfile: Dockerfile
        ports:
            - "51433:1433"
        volumes:
            - mssqlsystem:/var/opt/mssql
            - mssqluser:/var/opt/sqlserver
        environment:            
            SA_PASSWORD: "B@zaarDB_123"
            ACCEPT_EULA: "Y"

    bazaar-api:
        container_name: bazaar-api
        build:
            context: ../
            dockerfile: src/PM.BazaarCore.Services.WebApi/Dockerfile
        ports:
            - "80:80"
        depends_on:
            - mssql-server

volumes:
    mssqlsystem:
    mssqluser: